apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: k8s-assn
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: thekrao/be-app:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets 
                  key: DB_SERVER         
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets  
                  key: DB_USER           
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets  
                  key: DB_PASSWORD       
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets 
                  key: DB_NAME          
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets  
                  key: JWT_SECRET
            - name: DB_ENCRYPT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets  
                  key: DB_ENCRYPT  
            # - name: CORS_ORIGIN
            #   valueFrom:
            #     configMapKeyRef:
            #       name: backend-config 
            #       key: CORS_ORIGIN                         
          readinessProbe:
            httpGet: { path: /health, port: 3001 }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 3001 }
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits:   { cpu: "500m", memory: "256Mi" }
