name: Build and deploy frontend

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy frontend
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: app/ecommerce-app-frontend

      - name: Build frontend
        run: CI=false npm run build
        working-directory: app/ecommerce-app-frontend

      - name: Run tests
        run: npm test --if-present -- --passWithNoTests
        working-directory: app/ecommerce-app-frontend

      - name: Login to Azure
        if: github.event_name == 'workflow_dispatch'
        uses: azure/login@v2
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Set Terraform Azure credentials
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV

      - name: Setup Terraform
        if: github.event_name == 'workflow_dispatch'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Initialize Terraform backend
        if: github.event_name == 'workflow_dispatch'
        run: terraform init
        working-directory: terraform

      - name: Get Terraform outputs (rg, cluster_name)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "RG=$(terraform output -raw resource_group_name)" >> $GITHUB_ENV
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> $GITHUB_ENV
        working-directory: terraform

      - name: Set AKS Context
        if: github.event_name == 'workflow_dispatch'
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ env.CLUSTER_NAME }} 
          resource-group: ${{ env.RG }}

      - name: Verify access to cluster
        if: github.event_name == 'workflow_dispatch'
        run: kubectl get nodes

      - name: Get ingress lb IP 
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "INGRESS_LB_IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
          )" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build frontend docker image 
        if: github.event_name == 'workflow_dispatch'
        run: |
          docker build --build-arg REACT_APP_API_URL=http://$INGRESS_LB_IP/api \
           -t ${{ secrets.DOCKER_USERNAME }}/fe-app:latest .
        working-directory: app/ecommerce-app-frontend

      - name: Push frontend docker image
        if: github.event_name == 'workflow_dispatch'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fe-app:latest

      - name: Force rollout
        if: github.event_name == 'workflow_dispatch'
        run: kubectl rollout restart deployment/frontend-deploy -n k8s-assn
        working-directory: k8s/frontend
